apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
apiServer:
  extraArgs:
    cloud-provider: external
clusterName: <cluster-name>
controllerManager:
  extraArgs:
    cloud-provider: external
kubernetesVersion: stable # can use "stable"
controlPlaneEndpoint: <load-balancer-url:6443>
networking:
  dnsDomain: cluster.local
  podSubnet: <vpc-cidr>

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  name: <master-node-FQDN>
  kubeletExtraArgs:
    cloud-provider: external