apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: <token>
    apiServerEndpoint: <load-balancer-url:6443>
    caCertHashes:
      - <certificate-hash>
nodeRegistration:
  name: <worker-node-FQDN>
  kubeletExtraArgs:
    cloud-provider: external